improve disk usage of zap
blevesearch/zap pull request #15
Opened 2020-05-18 20:03 UTC by mschoch

Breaking change, to be released as new major version (v13.0.0)

One of the optimizations in v12 was to encode a special marker
value when a field/term had no location information stored.
Unfortunately that marker was math.MaxUint64, which when
encoded via Uvarint requires 10 bytes.  In practice, the number
of bytes required went up, not down as a result of this change.

Now, we use 0 as that special marker value.  This has been
determined to be safe as 0 could never be the actual address
of term location information, as there are other mandatory
sections earlier in the file (stored field index).

2020-05-18 20:03 UTC, mschoch commented
Still needs more testing, and some bleve release planning discussion.

2020-05-18 20:07 UTC, mschoch commented
In the same file that was originally used to identify the problem (very small) the overall sizes were:

```
v11: 406
v12: 426
v13: 399
```

This looks minor, but it can really add up if you have lots of terms without term vector information.

Using `bleve-blast` with 100k docs, and 1000 docs/batch (no forced merging, so there is some noise depending on where merging was at the time indexing completed):

```
v11: 798M
v12: 1.6G
v13: 631M
```

2020-05-19 02:45 UTC, sreekanth-cb requested changes
Perhaps we need to consider this change for docValues too?
ref- https://github.com/blevesearch/zap/blob/fa29047c37898c01e253b3265ff6031fed8cd280/build.go#L29

2020-05-19 03:08 UTC, sreekanth-cb reviewed
As this is at a field level marker for docValues, savings won't be significant. But it adds some consistency in the way we represent "non encoded" values?

2020-05-19 20:45 UTC, fproulx-dfuse commented
Is there any chance that this will get merged very soon to address the builder bug ?
We had set aside time to reprocess our indices with the new version, but now this is a showstopper.

Thanks.

2020-05-19 23:25 UTC, mschoch commented
@fproulx-dfuse I had planned to do some more testing before merging it, but given that Bleve 1.0.x does not default to scorch, and if you choose scorch it still defaults to v11, users have to go out of there way to enable this.  So I am more comfortable moving forward wit that in mind.

That said, I would still like to get approval from @sreekanth-cb first so we maintain our typical review process.

2020-05-20 02:32 UTC, sreekanth-cb approved these changes

2020-05-20 12:35 UTC, mschoch commented
@fproulx-dfuse sorry there will be a delay getting this merged, I have run into an issue in my testing this morning.

2020-05-21 15:21 UTC, sreekanth-cb approved these changes

2020-05-21 15:23 UTC, sreekanth-cb approved these changes

2020-05-22 14:38 UTC, mschoch commented
We found additional problems related to the docValues change.  As that did not contribute significantly to the disk space usage, we have reverted that portion of the change, so that we can get the more important fix merged promptly.

2020-05-22 14:52 UTC, sreekanth-cb approved these changes

2020-05-22 17:22 UTC, merged